# Week 1

In [1]:
def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result

In [2]:
import numpy as np
a = np.random.rand(20,20)
b= np.random.rand(20,20)

In [3]:
#l2_dist(np.reshape(a,(20*20)),np.reshape(b,(20*20,1)))
#l2_dist(np.reshape(a,(20*20)),np.reshape(b,(20*20)))
#l2_dist(a.T,b.T)
l2_dist(a,b)

8.054003793541733

In [4]:
a1 = np.random.rand(4)
a2=np.random.rand(4,1)
a3=np.array([[1,2,3,4]])
a4=np.arange(1,4,1)
a5=np.linspace(1,4,4)

In [5]:
a5.shape == a1.shape

True

In [6]:
a1.shape == a2.shape

False

In [7]:
a3.shape == a4.shape

False

In [8]:
import numpy as np

old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0
print(old)

[[0 0 1]
 [1 1 1]]


In [9]:
r = np.array([[0,1,2,3,4,5],[6,7,8,9,10,11],[12,13,14,15,16,17],[18,19,20,21,22,23],[24,25,26,27,28,29],[30,31,32,33,34,35]])

In [10]:
r[[2,4],[2,4]]

array([14, 28])

In [11]:
import re
s = 'ACBCAC'

In [12]:
re.findall('^AC', s)

['AC']

In [13]:
re.findall('[^A]C', s)

['BC']

In [14]:
re.findall('^[AC]', s)

['A']

In [15]:
re.findall('[A]', s)

['A', 'A']

In [16]:
s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)
print(L)

5


In [17]:
text = 'Office of Research Administration: (734) 647-6333 | 4325 North Quad Office of Budget and Financial Administration: (734) 647-8044 | 309 Maynard, Suite 205 Health Informatics Program: (734) 763-2285 | 333 Maynard, Suite 500 Office of the Dean: (734) 647-3576 | 4322 North Quad UMSI Engagement Center: (734) 763-1251 | 777 North University Faculty Adminstrative Support Staff: (734) 764-9376 | 4322 North Quad'

In [18]:
re.findall("[(]\d{3}[)]\s\d{3}[-]\d{4}", text)

['(734) 647-6333',
 '(734) 647-8044',
 '(734) 763-2285',
 '(734) 647-3576',
 '(734) 763-1251',
 '(734) 764-9376']

In [19]:
text2 = 'I refer to https://google.com and I never refer http://www.baidu.com if I have to search anything'

In [20]:
re.findall("(?<=[https]:\/\/)([A-Za-z0-9.]*)", text2)

['google.com', 'www.baidu.com']

In [21]:
text=r'''Everyone has the following fundamental freedoms:
(a) freedom of conscience and religion;
(b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
(c) freedom of peaceful assembly; and
(d) freedom of association.
'''

In [22]:
pattern = '[a-d]'
print(len(re.findall(pattern,text)))

40


In [23]:
simple_string = """Amy is 5 years old, and her sister Mary is 2 years old. 
    Ruth and Peter, their parents, have 3 kids."""

In [24]:
re.findall("[A-Z][a-z]*", simple_string)

['Amy', 'Mary', 'Ruth', 'Peter']

In [25]:
import re
def names():
    simple_string = """Amy is 5 years old, and her sister Mary is 2 years old. 
    Ruth and Peter, their parents, have 3 kids."""

    result = re.findall("[A-Z][a-z]*", simple_string)
    return result
    #raise NotImplementedError()

In [26]:
names()

['Amy', 'Mary', 'Ruth', 'Peter']

In [27]:
assert len(names()) == 4, "There are four names in the simple_string"

In [28]:
grades = '''Ronald Mayr: A
Bell Kassulke: B
Jacqueline Rupp: A 
Alexander Zeller: C
Valentina Denk: C 
Simon Loidl: B 
Elias Jovanovic: B 
Stefanie Weninger: A 
Fabian Peer: C 
Hakim Botros: B
Emilie Lorentsen: B
Herman Karlsen: C
Nathalie Delacruz: C
Casey Hartman: C
Lily Walker : A
Gerard Wang: C
Tony Mcdowell: C
Jake Wood: B
Fatemeh Akhtar: B
Kim Weston: B
Nicholas Beatty: A
Kirsten Williams: C
Vaishali Surana: C
Coby Mccormack: C
Yasmin Dar: B
Romy Donnelly: A
Viswamitra Upandhye: B
Kendrick Hilpert: A
Killian Kaufman: B
Elwood Page: B
Mukti Patel: A
Emily Lesch: C
Elodie Booker: B
Jedd Kim: A
Annabel Davies: A
Adnan Chen: B
Jonathan Berg: C
Hank Spinka: B
Agnes Schneider: C
Kimberly Green: A
Lola-Rose Coates: C
Rose Christiansen: C
Shirley Hintz: C
Hannah Bayer: B
'''

In [29]:
re.findall("[A-Z][a-z]*\s[A-Z][a-z]*\:\s[B]", grades)

['Bell Kassulke: B',
 'Simon Loidl: B',
 'Elias Jovanovic: B',
 'Hakim Botros: B',
 'Emilie Lorentsen: B',
 'Jake Wood: B',
 'Fatemeh Akhtar: B',
 'Kim Weston: B',
 'Yasmin Dar: B',
 'Viswamitra Upandhye: B',
 'Killian Kaufman: B',
 'Elwood Page: B',
 'Elodie Booker: B',
 'Adnan Chen: B',
 'Hank Spinka: B',
 'Hannah Bayer: B']

In [123]:
def grades():
    grades = '''Ronald Mayr: A
Bell Kassulke: B
Jacqueline Rupp: A 
Alexander Zeller: C
Valentina Denk: C 
Simon Loidl: B 
Elias Jovanovic: B 
Stefanie Weninger: A 
Fabian Peer: C 
Hakim Botros: B
Emilie Lorentsen: B
Herman Karlsen: C
Nathalie Delacruz: C
Casey Hartman: C
Lily Walker : A
Gerard Wang: C
Tony Mcdowell: C
Jake Wood: B
Fatemeh Akhtar: B
Kim Weston: B
Nicholas Beatty: A
Kirsten Williams: C
Vaishali Surana: C
Coby Mccormack: C
Yasmin Dar: B
Romy Donnelly: A
Viswamitra Upandhye: B
Kendrick Hilpert: A
Killian Kaufman: B
Elwood Page: B
Mukti Patel: A
Emily Lesch: C
Elodie Booker: B
Jedd Kim: A
Annabel Davies: A
Adnan Chen: B
Jonathan Berg: C
Hank Spinka: B
Agnes Schneider: C
Kimberly Green: A
Lola-Rose Coates: C
Rose Christiansen: C
Shirley Hintz: C
Hannah Bayer: B
'''

    result = re.findall("(\w*\s\w*)\:\s[B]", grades)
    return result
    #raise NotImplementedError()

In [124]:
assert len(grades()) == 16

In [125]:
print(grades())

['Bell Kassulke', 'Simon Loidl', 'Elias Jovanovic', 'Hakim Botros', 'Emilie Lorentsen', 'Jake Wood', 'Fatemeh Akhtar', 'Kim Weston', 'Yasmin Dar', 'Viswamitra Upandhye', 'Killian Kaufman', 'Elwood Page', 'Elodie Booker', 'Adnan Chen', 'Hank Spinka', 'Hannah Bayer']


In [32]:
with open(r"C:\Users\e3dy0\Downloads\logdata.txt", "r") as file:
        logdata = file.read()

In [53]:
host = re.findall("(?P<host>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})", logdata)

In [54]:
print(len(host))

979


In [55]:
user = re.findall("\s\-\s(?P<user_name>.\w*)", logdata)

In [59]:
print(len(user))

979


In [58]:
time = re.findall("(?P<time>\[.*\])", logdata)

In [60]:
print(len(time))

979


In [61]:
request = re.findall("\"(?P<request>.*)\"", logdata)

In [64]:
print(len(request))

979


In [66]:
full_match = re.findall("(?P<host>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\s\-\s(?P<user_name>.\w*)\s*(?P<time>\[.*\])\s*\"(?P<request>.*)\"", logdata)

In [114]:
result

NameError: name 'result3' is not defined

In [121]:
import re
def logs():
    with open(r"C:\Users\e3dy0\Downloads\logdata.txt", "r") as file:
        logdata = file.read()
        pattern="""
            (?P<host>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})
            \s\-\s(?P<user_name>.\w*)
            \s*\[(?P<time>.*)\]\s*
            \"(?P<request>.*)\"
            """
        result = list()
        for item in re.finditer(pattern,logdata,re.VERBOSE):
            result.append(item.groupdict())
    
    return result

In [122]:
print(len(logs()))

979


# Week 2